version: '3'
services:
  frontend:
    command: sh -c "npm rebuild esbuild && npm run dev"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    stdin_open: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - database
    environment:
      - DB_HOST=postgres
      - DB_PORT=6000
    volumes:
      - ./backend:/app

  database:
    image: postgres
    container_name: database
    ports:
      - "6000:5432"
    restart: always
    environment:
      - POSTGRES_DB=chatapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
