version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:4000:4000"
    depends_on:
      - database
    volumes:
      - ./backend:/app

  database:
    image: postgres
    ports:
      - "0.0.0.0:6000:5432"
    restart: always
    environment:
      - POSTGRES_DB=chatapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "placeholder@example.com"
      PGADMIN_DEFAULT_PASSWORD: "fakepassword123!"
    ports:
      - "16543:80"
    depends_on:
      - database

volumes:
  postgres-data:
